apiVersion: v1
kind: Service
metadata: 
    name: shiny-db-svc-{{ .Values.version }}
spec:
  selector:
    app: shiny-db-{{ .Values.version }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP