apiVersion: v1
kind: Service
metadata:
  name: shiny-auth-loadbalancer-{{ .Values.version }}
spec:
  selector:
    app: shiny-auth-{{ .Values.version }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.shinyAppPort }}
  type: LoadBalancer